version: "3"

services:
  pgmaster:
    image: postgres:10.3
    container_name: pgpool-cluster-pgmaster
    volumes:
      - ./_data/db_pgmaster:/var/lib/postgresql/data
    ports:
      - 3000:5432
    environment:
      - POSTGRES_DB=pgmaster
      - POSTGRES_USER=pgmaster
      - POSTGRES_PASSWORD=pgmaster
    networks:
      - pg-network

  pgslave1:
    image: postgres:10.3
    container_name: pgpool-cluster-pgslave1
    volumes:
      - ./_data/db_pgslave1:/var/lib/postgresql/data
    ports:
      - 3001:5432
    environment:
      - POSTGRES_DB=pgmaster
      - POSTGRES_USER=pgmaster
      - POSTGRES_PASSWORD=pgmaster
    networks:
      - pg-network

  pgslave2:
    image: postgres:10.3
    container_name: pgpool-cluster-pgslave2
    volumes:
      - ./_data/db_pgslave2:/var/lib/postgresql/data
    ports:
      - 3002:5432
    environment:
      - POSTGRES_DB=pgmaster
      - POSTGRES_USER=pgmaster
      - POSTGRES_PASSWORD=pgmaster
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgpool-cluster-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "valmor@threepixels.com.br"
      PGADMIN_DEFAULT_PASSWORD: pgmaster
    ports:
      - 3003:80
    links:
      - pgmaster
      - pgslave1
      - pgslave2
    networks:
      - pg-network

  pgpool:
    image: rueian/pgpool:3.7.5-debian9
    container_name: pgpool-cluster-pgpool
    restart: always
    environment:
      - PCP_USER=pgmaster
      - PCP_PASSWORD=pgmaster
      - CHECK_USER=pgmaster
      - CHECK_PASSWORD=pgmaster
      - DB_USERS=pgmaster:pgmaster
    ports:
      - 3004:5432
      - 9898:9898
    volumes:
      - ./pcp.conf:/etc/pgpool/pcp.conf
      - ./pgpool.conf:/etc/pgpool/pgpool.conf
      - ./pool_hba.conf:/etc/pgpool/pool_hba.conf
      - ./pool_passwd:/etc/pgpool/pool_passwd
      - ./pcp.conf:/etc/pgpool2/pcp.conf
      - ./pgpool.conf:/etc/pgpool2/pgpool.conf
      - ./pool_hba.conf:/etc/pgpool2/pool_hba.conf
      - ./pool_passwd:/etc/pgpool2/pool_passwd
    links:
      - pgmaster
      - pgslave1
      - pgslave2
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge
